name = "sundaeswap-finance/aicone"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'sundaeswap-finance/aicone'"

[repository]
user = "sundaeswap-finance"
project = "aicone"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
